### ISSUE TITLE
Navigation bar contents are not distinct

### ISSUE THREAD

**Issue by vignesh17** [astronomersiva/Map-My-Problems#1]
After login using the user account in the navigation bar the option  show closed complaint and log out are placed so closely that it looks like a single option.
![image](https://cloud.githubusercontent.com/assets/10937830/11443863/ab69cbf2-9546-11e5-922d-40217aaec8fd.png)

**Comment by astronomersiva** [comment]
I am carrying out some UI changes and this is the latest in my version:
![image](https://cloud.githubusercontent.com/assets/7725225/11443921/495c5f5a-9547-11e5-9ef8-0283ed857819.png)

However, what you say makes sense and I think it will be better to leave the navbar only for purposes like logout, update profile, etc. and include the 'Show Closed Complaints' as a map control itself(similar to Show Live Traffic).
